### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Vitalis-real/course_project#1]
1)
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.
![image](https://user-images.githubusercontent.com/8464662/198815588-ce80e1d7-26fc-4255-a3ad-f382e3334641.png)

2)

Модификатор не может использоваться без класса блока или класса элемента, это нарушает основные концепции БЭМ.
Подробная информация представлена в презентации урока или в записи трансляции (дополнительная ссылка к уроку в документации курса).
Справочник https://ru.bem.info/methodology/quick-start/

![image](https://user-images.githubusercontent.com/8464662/198815617-b0c637ef-fcd1-4c48-8bb8-3539424e4881.png)

**Comment by Vitalis-real** [comment]
Выполнена работа над ошибками!

https://vitalis-real.github.io/course_project/

https://github.com/Vitalis-real/course_project



сб, 29 окт. 2022 г. в 07:32, Andrii Fomenko ***@***.***>:

**Comment by Alecto** [comment]
прошу присылать ответы почтой, а не через гитхаб

сб, 29 жовт. 2022 р. о 10:36 Vitalii ***@***.***> пише:

**Comment by Alecto** [comment]
Сообщите пожалуйста название (день + время) группы + ваши имя фамилию.
В переписке эта информация отсуствует.

сб, 29 жовт. 2022 р. о 11:53 Андрей Фоменко ***@***.***>
пише:
